apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  ports:
  - name: "8084"
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: notifications
  type: ClusterIP
