services:
  reservations: 
    build: 
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    ports:
      - '8080:8080'
    env_file:
      - ./apps/reservations/.env  
    volumes:
      - .:/usr/src/app
  auth: 
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '8081:8081'
    env_file:
      - ./apps/auth/.env
    volumes:
      - .:/usr/src/app
  mongo: 
    image: mongo